package com.duycomp.downloader.core.designsystem.theme

import androidx.compose.ui.graphics.Color

val light_primary = Color(0xFF006783)
val light_onPrimary = Color(0xFFFFFFFF)
val light_primaryContainer = Color(0xFFBDE9FF)
val light_onPrimaryContainer = Color(0xFF001F2A)
val light_secondary = Color(0xFF4D616C)
val light_onSecondary = Color(0xFFFFFFFF)
val light_secondaryContainer = Color(0xFFD0E6F2)
val light_onSecondaryContainer = Color(0xFF081E27)
val light_tertiary = Color(0xFF5D5B7D)
val light_onTertiary = Color(0xFFFFFFFF)
val light_tertiaryContainer = Color(0xFFE3DFFF)
val light_onTertiaryContainer = Color(0xFF191836)
val light_error = Color(0xFFBA1A1A)
val light_errorContainer = Color(0xFFFFDAD6)
val light_onError = Color(0xFFFFFFFF)
val light_onErrorContainer = Color(0xFF410002)
val light_background = Color(0xFFFBFCFE)
val light_onBackground = Color(0xFF191C1E)
val light_surface = Color(0xFFFBFCFE)
val light_onSurface = Color(0xFF191C1E)
val light_surfaceVariant = Color(0xFFDCE4E9)
val light_onSurfaceVariant = Color(0xFF40484C)
val light_outline = Color(0xFF70787D)
val light_inverseOnSurface = Color(0xFFEFF1F3)
val light_inverseSurface = Color(0xFF2E3132)
val light_inversePrimary = Color(0xFF65D3FF)
val light_shadow = Color(0xFF000000)
val light_surfaceTint = Color(0xFF006783)
val light_surfaceTintColor = Color(0xFF006783)

//val dark_primary = Color(0xFF65D3FF)
val dark_primary = Color(0xFF0C799B)
val dark_onPrimary = Color(0xFFBDE9FF)
val dark_primaryContainer = Color(0xFF004D64)
val dark_onPrimaryContainer = Color(0xFFBDE9FF)
val dark_secondary = Color(0xFFB4CAD6)
val dark_onSecondary = Color(0xFF1F333C)
val dark_secondaryContainer = Color(0xFF354A53)
val dark_onSecondaryContainer = Color(0xFFD0E6F2)
val dark_tertiary = Color(0xFFC6C2EA)
val dark_onTertiary = Color(0xFF2E2D4D)
val dark_tertiaryContainer = Color(0xFF454364)
val dark_onTertiaryContainer = Color(0xFFE3DFFF)
val dark_error = Color(0xFFFFB4AB)
val dark_errorContainer = Color(0xFF93000A)
val dark_onError = Color(0xFF690005)
val dark_onErrorContainer = Color(0xFFFFDAD6)
val dark_background = Color(0xFF191C1E)
val dark_onBackground = Color(0xFFE1E2E4)
val dark_surface = Color(0xFF191C1E)
val dark_onSurface = Color(0xFFE1E2E4)
val dark_surfaceVariant = Color(0xFF40484C)
val dark_onSurfaceVariant = Color(0xFFC0C8CD)
val dark_outline = Color(0xFF8A9297)
val dark_inverseOnSurface = Color(0xFF191C1E)
val dark_inverseSurface = Color(0xFFE1E2E4)
val dark_inversePrimary = Color(0xFF006783)
val dark_shadow = Color(0xFF000000)
val dark_surfaceTint = Color(0xFF65D3FF)
val dark_surfaceTintColor = Color(0xFF65D3FF)


val seed = Color(0xFF0A627D)

val bkg_icon = Color(0xFF1D1D1D)

